version: '3'
services:
    angular-ui:
        build: .
        ports:
            - "4200:4200"
        container_name: angular-ui
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
        #    - /usr/src/app/app-ui/node_modules

volumes:
    node_modules:
